//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CicloMania.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class envio
    {
        public int envioid { get; set; }
        public int facturaid { get; set; }
        public string direccion { get; set; }
        public System.DateTime fechaEnvio { get; set; }
        public string estado { get; set; }
    
        public virtual factura factura { get; set; }
    }
}
