//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CicloMania.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class inventario
    {
        [Display(Name = "ID inventario")]
        [Required(ErrorMessage = "El ID inventario es un campo obligatorio")]
        public int inventarioid { get; set; }
        [Display(Name = "Código del articulo")]
        [Required(ErrorMessage = "La codigo del articulo es un campo obligatorio")]
        public string codigoArticulo { get; set; }
        [Display(Name = "Cantidad en stock")]
        [Required(ErrorMessage = "Cantidad en stock es un campo obligatorio")]
        [Range(1, 9999, ErrorMessage = "Cantidad en stock no debe sobrepasar 5 dígitos")]
        public int cantidadStock { get; set; }
        [Display(Name = "ID proveedor")]
        [Required(ErrorMessage = "ID proveedor es un campo obligatorio")]
        [Range(1, 9999, ErrorMessage = "ID proveedor no debe sobrepasar 5 dígitos")]
        public int proveeid { get; set; }
    
        public virtual proveedor proveedor { get; set; }
    }
}
