//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CicloMania.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventario
    {
        public int inventarioid { get; set; }
        public string codigoArticulo { get; set; }
        public int cantidadStock { get; set; }
        public int proveeid { get; set; }
    
        public virtual proveedor proveedor { get; set; }
    }
}
