//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CicloMania.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mantenimientos
    {
        public int Num_Mantenimiento { get; set; }
        public string cedula { get; set; }
        public string tipoMantenimiento { get; set; }
        public string detallesArreglo { get; set; }
    }
}
